In [31]:
import pandas as pd
import numpy as np
import datetime

In [44]:
d={
    'hash'          :'category',
    'trajectory_id' :'category',
    'time_entry'    :'category',
    'time_exit'    :'category',
    'vmax':'float64',
    'vmin':'float64',
    'vmean':'float64',
    'x_entry':'float64',
    'y_entry':'float64',
    'x_exit':'float64',
    'y_exit':'float64'
}

In [45]:
train = pd.read_csv('./input/data_train.csv',dtype=d).drop(columns=['Unnamed: 0'])
test = pd.read_csv('./input/data_test.csv',dtype=d).drop(columns=['Unnamed: 0'])
train['time_entry']=train['time_entry'].astype('datetime64[ns]')
trajectory_id = test['trajectory_id']

In [46]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814262 entries, 0 to 814261
Data columns (total 11 columns):
hash             814262 non-null category
trajectory_id    814262 non-null category
time_entry       814262 non-null datetime64[ns]
time_exit        814262 non-null category
vmax             256769 non-null float64
vmin             256769 non-null float64
vmean            270778 non-null float64
x_entry          814262 non-null float64
y_entry          814262 non-null float64
x_exit           814262 non-null float64
y_exit           814262 non-null float64
dtypes: category(3), datetime64[ns](1), float64(7)
memory usage: 114.2 MB

In [23]:
train[0:20]

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit
0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,NaN,NaN,NaN,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07
1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,NaN,NaN,NaN,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07
2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,NaN,NaN,NaN,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07
3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,NaN,NaN,NaN,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07
4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,14:38:09,14:38:09,NaN,NaN,NaN,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07
5,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_5,15:02:31,15:18:33,NaN,NaN,NaN,3.744945e+06,-1.928183e+07,3.744785e+06,-1.928148e+07
6,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_0,14:29:23,14:29:23,0.000000,0.000000,0.000000,3.749450e+06,-1.926506e+07,3.749450e+06,-1.926506e+07
7,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_1,14:39:49,14:39:49,0.000000,0.000000,0.000000,3.749090e+06,-1.926726e+07,3.749090e+06,-1.926726e+07
8,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_2,14:50:14,14:50:14,0.507809,0.507809,0.507809,3.749042e+06,-1.926632e+07,3.749042e+06,-1.926632e+07
9,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_3,15:00:32,15:29:48,1.149404,1.149404,1.149404,3.749088e+06,-1.926605e+07,3.749610e+06,-1.926594e+07
10,0001f97b99a80f18f62e2d44e54ef33d_3,traj_0001f97b99a80f18f62e2d44e54ef33d_3_0,11:37:06,11:52:08,32.196255,32.196255,32.196255,3.771461e+06,-1.910413e+07,3.757004e+06,-1.929698e+07
11,0001f97b99a80f18f62e2d44e54ef33d_3,traj_0001f97b99a80f18f62e2d44e54ef33d_3_1,14:34:35,15:19:51,30.167742,30.167742,30.167742,3.758738e+06,-1.937594e+07,3.769687e+06,-1.914258e+07
12,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_1,09:56:08,09:56:08,NaN,NaN,NaN,3.765544e+06,-1.917227e+07,3.765544e+06,-1.917227e+07
13,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_2,10:17:00,10:17:00,NaN,NaN,NaN,3.766338e+06,-1.917967e+07,3.766338e+06,-1.917967e+07
14,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_4,12:38:33,12:38:33,NaN,NaN,NaN,3.767863e+06,-1.917851e+07,3.767863e+06,-1.917851e+07
15,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_5,13:57:02,13:59:00,NaN,NaN,NaN,3.767864e+06,-1.917860e+07,3.767865e+06,-1.917859e+07
16,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_6,14:09:16,14:09:16,NaN,NaN,NaN,3.763879e+06,-1.921491e+07,3.763879e+06,-1.921491e+07
17,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_7,14:19:32,14:19:32,NaN,NaN,NaN,3.759740e+06,-1.921491e+07,3.759740e+06,-1.921491e+07
18,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_8,14:29:36,14:29:36,NaN,NaN,NaN,3.756596e+06,-1.921483e+07,3.756596e+06,-1.921483e+07
19,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_9,14:39:37,14:59:01,NaN,NaN,NaN,3.760046e+06,-1.923746e+07,3.768391e+06,-1.920211e+07

In [24]:
test[:20]

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit
0,00032f51796fd5437b238e3a9823d13d_31,traj_00032f51796fd5437b238e3a9823d13d_31_0,11:43:17,11:50:17,NaN,NaN,NaN,3.773413e+06,-1.909828e+07,3.773111e+06,-1.914508e+07
1,00032f51796fd5437b238e3a9823d13d_31,traj_00032f51796fd5437b238e3a9823d13d_31_2,12:21:37,12:21:37,0.00,0.00,0.00,3.773199e+06,-1.914354e+07,3.773199e+06,-1.914354e+07
2,00032f51796fd5437b238e3a9823d13d_31,traj_00032f51796fd5437b238e3a9823d13d_31_3,12:34:27,13:14:11,NaN,NaN,NaN,3.763760e+06,-1.921342e+07,3.771757e+06,-1.911092e+07
3,00032f51796fd5437b238e3a9823d13d_31,traj_00032f51796fd5437b238e3a9823d13d_31_4,13:25:33,13:43:13,NaN,NaN,NaN,3.773385e+06,-1.911344e+07,3.773131e+06,-1.914465e+07
4,00032f51796fd5437b238e3a9823d13d_31,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,NaN,NaN,NaN,3.773118e+06,-1.914490e+07,NaN,NaN
5,000479418b5561ab694a2870cc04fd43_25,traj_000479418b5561ab694a2870cc04fd43_25_0,08:08:23,08:20:08,17.29,17.29,17.29,3.771380e+06,-1.933274e+07,3.769933e+06,-1.934095e+07
6,000479418b5561ab694a2870cc04fd43_25,traj_000479418b5561ab694a2870cc04fd43_25_6,12:08:23,12:13:24,NaN,NaN,NaN,3.771380e+06,-1.933274e+07,3.769983e+06,-1.934265e+07
7,000479418b5561ab694a2870cc04fd43_25,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,NaN,NaN,NaN,3.769978e+06,-1.934136e+07,NaN,NaN
8,000506a39775e5bca661ac80e3f466eb_29,traj_000506a39775e5bca661ac80e3f466eb_29_1,08:45:05,08:50:33,NaN,NaN,NaN,3.760880e+06,-1.910042e+07,3.759312e+06,-1.908280e+07
9,000506a39775e5bca661ac80e3f466eb_29,traj_000506a39775e5bca661ac80e3f466eb_29_2,11:09:02,11:09:02,NaN,NaN,NaN,3.755349e+06,-1.916135e+07,3.755349e+06,-1.916135e+07
10,000506a39775e5bca661ac80e3f466eb_29,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,NaN,NaN,NaN,3.757468e+06,-1.923860e+07,NaN,NaN
11,0005401ceddaf27a9b7f0d42ef1fbe95_1,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_0,09:10:03,09:10:03,NaN,NaN,NaN,3.751328e+06,-1.916236e+07,3.751328e+06,-1.916236e+07
12,0005401ceddaf27a9b7f0d42ef1fbe95_1,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_1,09:37:39,09:37:39,NaN,NaN,NaN,3.751349e+06,-1.916284e+07,3.751349e+06,-1.916284e+07
13,0005401ceddaf27a9b7f0d42ef1fbe95_1,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,NaN,NaN,NaN,3.760505e+06,-1.935500e+07,NaN,NaN
14,00063a4f6c12e1e4de7d876580620667_3,traj_00063a4f6c12e1e4de7d876580620667_3_1,08:48:38,09:33:56,NaN,NaN,NaN,3.747364e+06,-1.927846e+07,3.774308e+06,-1.911005e+07
15,00063a4f6c12e1e4de7d876580620667_3,traj_00063a4f6c12e1e4de7d876580620667_3_2,12:53:38,12:58:19,NaN,NaN,NaN,3.776268e+06,-1.918284e+07,3.776260e+06,-1.918272e+07
16,00063a4f6c12e1e4de7d876580620667_3,traj_00063a4f6c12e1e4de7d876580620667_3_3,14:18:20,14:35:02,NaN,NaN,NaN,3.776264e+06,-1.918289e+07,3.766296e+06,-1.917029e+07
17,00063a4f6c12e1e4de7d876580620667_3,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,NaN,NaN,NaN,3.766319e+06,-1.917013e+07,NaN,NaN
18,0006535be25bb52dd06983447880c964_5,traj_0006535be25bb52dd06983447880c964_5_0,00:37:06,00:37:06,NaN,NaN,NaN,3.769811e+06,-1.935067e+07,3.769811e+06,-1.935067e+07
19,0006535be25bb52dd06983447880c964_5,traj_0006535be25bb52dd06983447880c964_5_5,09:00:16,09:00:16,NaN,NaN,NaN,3.774369e+06,-1.926659e+07,3.774369e+06,-1.926659e+07

In [25]:
def within_measure(x, y):
    #  3750901.5068 ≤ 𝑥 ≤ 3770901.5068
    #  −19268905.6133 ≤ 𝑦 ≤ −19208905.6133
    if 3750901.5068 <= x and x <= 3770901.5068 and -19268905.6133 <= y and y <= -19208905.6133:
        return 1
    else:
        return 0

def time_to_sec(values):
    return pd.to_timedelta(values).dt.total_seconds().astype(int)

In [26]:
X = train['x_exit'].values 
Y = train['y_exit'].values
city = [within_measure(x, y) for x,y in zip(X,Y)]

In [32]:
test2 = test[(test['time_exit']>datetime.timedelta(15,0,0))&(test['time_exit']<datetime.timedelta(16,0,0))]

TypeError: '>' not supported between instances of 'str' and 'datetime.timedelta'

In [5]:
train.time_entry = time_to_sec(train.time_entry)
train.time_exit = time_to_sec(train.time_exit)
test.time_entry = time_to_sec(test.time_entry)
test.time_exit = time_to_sec(test.time_exit)

In [6]:
for col in test.columns:
    test[col].fillna(test[col].mode()[0], inplace=True)
    train[col].fillna(train[col].mode()[0], inplace=True)

In [7]:
from sklearn.ensemble import RandomForestClassifier

X_train = train.drop(columns=['hash','trajectory_id'])
X_test = test.drop(columns=['hash','trajectory_id'])

model = RandomForestClassifier(n_estimators=100, max_depth=2,
                             random_state=0)
model.fit(X_train, city)


pred = model.predict(X_test)

In [17]:
submission= pd.DataFrame()
submission['id']=trajectory_id 
submission['target'] = pred
submission.to_csv('./output/submission.csv',index=False)    
submission[:20]

                                             id  target
0    traj_00032f51796fd5437b238e3a9823d13d_31_0       0
1    traj_00032f51796fd5437b238e3a9823d13d_31_2       0
2    traj_00032f51796fd5437b238e3a9823d13d_31_3       0
3    traj_00032f51796fd5437b238e3a9823d13d_31_4       0
4    traj_00032f51796fd5437b238e3a9823d13d_31_5       0
5    traj_000479418b5561ab694a2870cc04fd43_25_0       0
6    traj_000479418b5561ab694a2870cc04fd43_25_6       0
7   traj_000479418b5561ab694a2870cc04fd43_25_10       0
8    traj_000506a39775e5bca661ac80e3f466eb_29_1       0
9    traj_000506a39775e5bca661ac80e3f466eb_29_2       0
10   traj_000506a39775e5bca661ac80e3f466eb_29_5       1
11    traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_0       0
12    traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_1       0
13    traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4       0
14    traj_00063a4f6c12e1e4de7d876580620667_3_1       0
15    traj_00063a4f6c12e1e4de7d876580620667_3_2       0
16    traj_00063a4f6c12e1e4de7d876580620667_3_3       0
17    traj_00063a4f6c12e1e4de7d876580620667_3_4       0
18    traj_0006535be25bb52dd06983447880c964_5_0       0
19    traj_0006535be25bb52dd06983447880c964_5_5       0